Repository secvisogram/secvisogram, pull requests merged in 2021-12, with the labels that each got.

#206 Mandatory tests - fix 6.1.16
  app/lib/shared/Core/entities/DocumentEntity.js
  app/tests/shared/coreFixture.js
Labels: bug, csaf 2.0

#207 Mandatory tests - fix 6.1.24
  app/lib/shared/Core/entities/DocumentEntity/mandatoryTest_6_1_24.js
  app/tests/shared/coreFixture.js
Labels: bug, csaf 2.0

#212 Placeholder
  app/lib/SecvisogramPage/View/FormEditorTab/shared/definitions/Acknowledgments.js
  app/lib/SecvisogramPage/View/FormEditorTab/shared/definitions/Lang.js
Labels: enhancement

#211 Fix threats
  PREVIEW-TEMPLATING.md
  app/lib/SecvisogramPage/View/shared/HTMLTemplate.js
  app/lib/SecvisogramPage/View/shared/HTMLTemplate/Template.html
  app/lib/shared/Core/entities/DocumentEntity.js
Labels: bug

#218 Extended language tag check
  app/lib/shared/bcpLanguageTagChecker.js
  app/lib/shared/bcpLanguageTagChecker/extensions.json
  app/node_modules.d.ts
  app/tests/bcpLanguageTagChecker.js
  app/types.d.ts
  bin/cli.js
  bin/cli/parseLanguageTagExtensionList.js
  data/language-tag-extensions-registry.txt
  package.json
Labels: csaf 2.0

#219 Sort document keys during strip algorithm
  app/lib/shared/Core/entities/DocumentEntity.js
  app/lib/shared/sortObjectKeys.js
  app/tests/index.js
  app/tests/sortObjectKeys.js
Labels: enhancement
